/* isrs.c
 * This file is modified form Bram's Kernel Development Tutorial
 * set up the Interrupt Service Routines,
 * which handle excepitons generated by processor 
 */
// std
#include <type.h>
#include <vga.h>
// x86
#include <pm.h>
#include <isr.h>

#define DECLARE_ISR
/* int 0-31 is used to service exceptions! */
extern void isr0();
extern void isr1();
extern void isr2();
extern void isr3();
extern void isr4();
extern void isr5();
extern void isr6();
extern void isr7();
extern void isr8();
extern void isr9();
extern void isr10();
extern void isr11();
extern void isr12();
extern void isr13();
extern void isr14();
extern void isr15();
extern void isr16();
extern void isr17();
extern void isr18();
extern void isr19();
extern void isr20();
extern void isr21();
extern void isr22();
extern void isr23();
extern void isr24();
extern void isr25();
extern void isr26();
extern void isr27();
extern void isr28();
extern void isr29();
extern void isr30();
extern void isr31();
extern void isr_unknown();

// present, ring 0
void isrs_init()
{
    idt_set_gate(0, (uint32_t)isr0, 0x08, 0x8e);
    idt_set_gate(1, (uint32_t)isr1, 0x08, 0x8e);
    idt_set_gate(2, (uint32_t)isr2, 0x08, 0x8e);
    idt_set_gate(3, (uint32_t)isr3, 0x08, 0x8e);
    idt_set_gate(4, (uint32_t)isr4, 0x08, 0x8e);
    idt_set_gate(5, (uint32_t)isr5, 0x08, 0x8e);
    idt_set_gate(6, (uint32_t)isr6, 0x08, 0x8e);
    idt_set_gate(7, (uint32_t)isr7, 0x08, 0x8e);

    idt_set_gate(8, (uint32_t)isr8, 0x08, 0x8e);
    idt_set_gate(9, (uint32_t)isr9, 0x08, 0x8e);
    idt_set_gate(10, (uint32_t)isr10, 0x08, 0x8e);
    idt_set_gate(11, (uint32_t)isr11, 0x08, 0x8e);
    idt_set_gate(12, (uint32_t)isr12, 0x08, 0x8e);
    idt_set_gate(13, (uint32_t)isr13, 0x08, 0x8e);
    idt_set_gate(14, (uint32_t)isr14, 0x08, 0x8e);
    idt_set_gate(15, (uint32_t)isr15, 0x08, 0x8e);

    idt_set_gate(16, (uint32_t)isr16, 0x08, 0x8e);
    idt_set_gate(17, (uint32_t)isr17, 0x08, 0x8e);
    idt_set_gate(18, (uint32_t)isr18, 0x08, 0x8e);
    idt_set_gate(19, (uint32_t)isr19, 0x08, 0x8e);
    idt_set_gate(20, (uint32_t)isr20, 0x08, 0x8e);
    idt_set_gate(21, (uint32_t)isr21, 0x08, 0x8e);
    idt_set_gate(22, (uint32_t)isr22, 0x08, 0x8e);
    idt_set_gate(23, (uint32_t)isr23, 0x08, 0x8e);

    idt_set_gate(24, (uint32_t)isr24, 0x08, 0x8e);
    idt_set_gate(25, (uint32_t)isr25, 0x08, 0x8e);
    idt_set_gate(26, (uint32_t)isr26, 0x08, 0x8e);
    idt_set_gate(27, (uint32_t)isr27, 0x08, 0x8e);
    idt_set_gate(28, (uint32_t)isr28, 0x08, 0x8e);
    idt_set_gate(29, (uint32_t)isr29, 0x08, 0x8e);
    idt_set_gate(30, (uint32_t)isr30, 0x08, 0x8e);
    idt_set_gate(31, (uint32_t)isr31, 0x08, 0x8e);

    /* treat other interrupt as unkown interrupt */
    int i;
    for (i = 32; i < 256; i++){
        idt_set_gate(i,(uint32_t)isr_unknown, 0x08, 0x8e);
    }
}

char *exception_messages[] = {
    "Division By Zero\0",
    "Debug\0",
    "Non Maskable Interrupt\0",
    "Breakpoint\0",
    "Into Detected Overflow\0",
    "Out of Bounds\0",
    "Invalid Opcode\0",
    "No Coprocessor\0",

    "Double Fault\0",
    "Coprocessor Segment Overrun\0",
    "Bad TSS\0",
    "Segment Not Present\0",
    "Stack Fault\0",
    "General Protection Fault\0",
    "Page Fault\0",
    "Unknown Interrupt\0",

    "Coprocessor Fault\0",
    "Alignment Check\0",
    "Machine Check\0",
    "Reserved\0",
    "Reserved\0",
    "Reserved\0",
    "Reserved\0",
    "Reserved\0",

    "Reserved\0",
    "Reserved\0",
    "Reserved\0",
    "Reserved\0",
    "Reserved\0",
    "Reserved\0",
    "Reserved\0",
    "Reserved\0"
};

void fault_handler(struct regs_s *r){
    setcolor(COL_RED, COL_BLACK);
    if (r->int_no < 32){
        puts(exception_messages[r->int_no]);
        puts("Exception.\nSystem Halted!\n\0");
    }else{
        puts("Unkonwn Interrupt, System Halted!\n\0");
    }
    for (;;);
}
